# Generated by Django 5.2.5 on 2025-09-07 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lockedcontent',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'portrait'), ('landscape', 'landscape')], db_index=True, default='landscape', max_length=10),
        ),
        migrations.AddIndex(
            model_name='lockedcontent',
            index=models.Index(fields=['user', 'orientation', 'created_at'], name='render_lock_user_id_87125f_idx'),
        ),
    ]
