# Generated by Django 5.1.7 on 2025-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("func", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="videos/")),
                (
                    "transcoded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="transcoded_videos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
